name = "kdr"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_GOOGLE_ADSENSE = "pub-8204887027170024"
NEXT_PUBLIC_GA_TRACKING_ID = "GTM-NBT8TG6"